# Generated by Django 5.0.3 on 2024-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpTable',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('CompanyName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=128)),
                ('ConfirmPassword', models.CharField(max_length=128)),
            ],
        ),
    ]
