# Generated by Django 4.1.13 on 2024-04-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signuptable',
            old_name='CompanyName',
            new_name='User_Name',
        ),
        migrations.RemoveField(
            model_name='signuptable',
            name='ConfirmPassword',
        ),
    ]
