# Generated by Django 4.1.13 on 2024-04-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_companyname_signuptable_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuptable',
            name='Password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
